version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
      - auth
      - user
      - chat
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api # overrides CMD from dockerfile

  user:
    build:
      context: ./
      dockerfile: ./apps/user/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev user # overrides CMD from dockerfile

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth # overrides CMD from dockerfile

  chat:
    build:
      context: ./
      dockerfile: ./apps/chat/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev chat # overrides CMD from dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
